/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VolunteerUserIdRouteImport } from './routes/volunteer.$userId'
import { Route as VerifyRefRouteImport } from './routes/verify.$ref'
import { Route as AuthenticatedAppNgoRouteImport } from './routes/_authenticated/app.ngo'
import { Route as AuthenticatedAppFeedRouteImport } from './routes/_authenticated/app.feed'
import { Route as AuthenticatedAppEsgRouteImport } from './routes/_authenticated/app.esg'
import { Route as AuthenticatedAppAdminRouteImport } from './routes/_authenticated/app.admin'
import { Route as AuthenticatedAppProjectProjectIdRouteImport } from './routes/_authenticated/app.project.$projectId'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VolunteerUserIdRoute = VolunteerUserIdRouteImport.update({
  id: '/volunteer/$userId',
  path: '/volunteer/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRefRoute = VerifyRefRouteImport.update({
  id: '/verify/$ref',
  path: '/verify/$ref',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppNgoRoute = AuthenticatedAppNgoRouteImport.update({
  id: '/app/ngo',
  path: '/app/ngo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppFeedRoute = AuthenticatedAppFeedRouteImport.update({
  id: '/app/feed',
  path: '/app/feed',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppEsgRoute = AuthenticatedAppEsgRouteImport.update({
  id: '/app/esg',
  path: '/app/esg',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppAdminRoute = AuthenticatedAppAdminRouteImport.update({
  id: '/app/admin',
  path: '/app/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppProjectProjectIdRoute =
  AuthenticatedAppProjectProjectIdRouteImport.update({
    id: '/app/project/$projectId',
    path: '/app/project/$projectId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/verify/$ref': typeof VerifyRefRoute
  '/volunteer/$userId': typeof VolunteerUserIdRoute
  '/app/admin': typeof AuthenticatedAppAdminRoute
  '/app/esg': typeof AuthenticatedAppEsgRoute
  '/app/feed': typeof AuthenticatedAppFeedRoute
  '/app/ngo': typeof AuthenticatedAppNgoRoute
  '/app/project/$projectId': typeof AuthenticatedAppProjectProjectIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/verify/$ref': typeof VerifyRefRoute
  '/volunteer/$userId': typeof VolunteerUserIdRoute
  '/app/admin': typeof AuthenticatedAppAdminRoute
  '/app/esg': typeof AuthenticatedAppEsgRoute
  '/app/feed': typeof AuthenticatedAppFeedRoute
  '/app/ngo': typeof AuthenticatedAppNgoRoute
  '/app/project/$projectId': typeof AuthenticatedAppProjectProjectIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/verify/$ref': typeof VerifyRefRoute
  '/volunteer/$userId': typeof VolunteerUserIdRoute
  '/_authenticated/app/admin': typeof AuthenticatedAppAdminRoute
  '/_authenticated/app/esg': typeof AuthenticatedAppEsgRoute
  '/_authenticated/app/feed': typeof AuthenticatedAppFeedRoute
  '/_authenticated/app/ngo': typeof AuthenticatedAppNgoRoute
  '/_authenticated/app/project/$projectId': typeof AuthenticatedAppProjectProjectIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/verify/$ref'
    | '/volunteer/$userId'
    | '/app/admin'
    | '/app/esg'
    | '/app/feed'
    | '/app/ngo'
    | '/app/project/$projectId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/verify/$ref'
    | '/volunteer/$userId'
    | '/app/admin'
    | '/app/esg'
    | '/app/feed'
    | '/app/ngo'
    | '/app/project/$projectId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/onboarding'
    | '/verify/$ref'
    | '/volunteer/$userId'
    | '/_authenticated/app/admin'
    | '/_authenticated/app/esg'
    | '/_authenticated/app/feed'
    | '/_authenticated/app/ngo'
    | '/_authenticated/app/project/$projectId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  OnboardingRoute: typeof OnboardingRoute
  VerifyRefRoute: typeof VerifyRefRoute
  VolunteerUserIdRoute: typeof VolunteerUserIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/volunteer/$userId': {
      id: '/volunteer/$userId'
      path: '/volunteer/$userId'
      fullPath: '/volunteer/$userId'
      preLoaderRoute: typeof VolunteerUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/$ref': {
      id: '/verify/$ref'
      path: '/verify/$ref'
      fullPath: '/verify/$ref'
      preLoaderRoute: typeof VerifyRefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/ngo': {
      id: '/_authenticated/app/ngo'
      path: '/app/ngo'
      fullPath: '/app/ngo'
      preLoaderRoute: typeof AuthenticatedAppNgoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/feed': {
      id: '/_authenticated/app/feed'
      path: '/app/feed'
      fullPath: '/app/feed'
      preLoaderRoute: typeof AuthenticatedAppFeedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/esg': {
      id: '/_authenticated/app/esg'
      path: '/app/esg'
      fullPath: '/app/esg'
      preLoaderRoute: typeof AuthenticatedAppEsgRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/admin': {
      id: '/_authenticated/app/admin'
      path: '/app/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AuthenticatedAppAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/project/$projectId': {
      id: '/_authenticated/app/project/$projectId'
      path: '/app/project/$projectId'
      fullPath: '/app/project/$projectId'
      preLoaderRoute: typeof AuthenticatedAppProjectProjectIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppAdminRoute: typeof AuthenticatedAppAdminRoute
  AuthenticatedAppEsgRoute: typeof AuthenticatedAppEsgRoute
  AuthenticatedAppFeedRoute: typeof AuthenticatedAppFeedRoute
  AuthenticatedAppNgoRoute: typeof AuthenticatedAppNgoRoute
  AuthenticatedAppProjectProjectIdRoute: typeof AuthenticatedAppProjectProjectIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppAdminRoute: AuthenticatedAppAdminRoute,
  AuthenticatedAppEsgRoute: AuthenticatedAppEsgRoute,
  AuthenticatedAppFeedRoute: AuthenticatedAppFeedRoute,
  AuthenticatedAppNgoRoute: AuthenticatedAppNgoRoute,
  AuthenticatedAppProjectProjectIdRoute: AuthenticatedAppProjectProjectIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  OnboardingRoute: OnboardingRoute,
  VerifyRefRoute: VerifyRefRoute,
  VolunteerUserIdRoute: VolunteerUserIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
